version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: oteam_postgres_db
    restart: always
    environment:
      POSTGRES_USER: oteam_user
      POSTGRES_PASSWORD: oteam_password
      POSTGRES_DB: oteam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: