# .github/workflows/ci.yml
name: OTeam CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test # Add if you have backend tests
        run: npm run test # Ensure your test script is configured

  lint-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build # Next.js build can catch type errors
        run: npm run build
      # - name: Test # Add if you have frontend tests
      #   run: npm run test

  # Add build check if necessary, though build is part of lint-and-test-frontend